### ISSUE TITLE
Starting in Wayland fails

### ISSUE THREAD

**Issue by ghost** [flathub/com.super_productivity.SuperProductivity#2]
The below works from the terminal:
```
flatpak run com.super_productivity.SuperProductivity --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations
```
Log
```
flatpak run com.super_productivity.SuperProductivity --ozone-platform-hint=auto --enable-features=WaylandWindowDecorations                          
[3:1209/160207.217477:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Start app...
16:02:07.611 › { enabled: null, showDevTools: false, mode: 'bottom' }
[3:1209/160207.773980:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1209/160207.774154:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Saving backups to /home/user/.var/app/com.super_productivity.SuperProductivity/config/superProductivity/backups
16:02:07.895 › Saving backups to /home/user/.var/app/com.super_productivity.SuperProductivity/config/superProductivity/backups
[3:1209/160207.908646:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1209/160207.908859:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1209/160207.908965:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
16:02:09.543 › No custom styles detected at /home/user/.var/app/com.super_productivity.SuperProductivity/config/superProductivity/styles.css
ERR Global Shortcut registration failed: Ctrl+Shift+X
16:02:09.701 › Error: Global Shortcut registration failed: Ctrl+Shift+X
    at errorHandlerWithFrontendInform (/app/superproductivity/resources/app.asar/electron/error-handler-with-frontend-inform.js:10:18)
    at /app/superproductivity/resources/app.asar/electron/ipc-handler.js:181:101
    at Array.forEach (<anonymous>)
    at registerShowAppShortCuts (/app/superproductivity/resources/app.asar/electron/ipc-handler.js:140:18)
    at IpcMainImpl.<anonymous> (/app/superproductivity/resources/app.asar/electron/ipc-handler.js:110:9)
    at IpcMainImpl.emit (node:events:519:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86186)
    at WebContents.emit (node:events:519:28)
16:02:09.703 › Global Shortcut registration failed: Ctrl+Shift+X Error: Global Shortcut registration failed: Ctrl+Shift+X
    at errorHandlerWithFrontendInform (/app/superproductivity/resources/app.asar/electron/error-handler-with-frontend-inform.js:10:18)
    at /app/superproductivity/resources/app.asar/electron/ipc-handler.js:181:101
    at Array.forEach (<anonymous>)
    at registerShowAppShortCuts (/app/superproductivity/resources/app.asar/electron/ipc-handler.js:140:18)
    at IpcMainImpl.<anonymous> (/app/superproductivity/resources/app.asar/electron/ipc-handler.js:110:9)
    at IpcMainImpl.emit (node:events:519:28)
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:86186)
    at WebContents.emit (node:events:519:28)
16:02:09.703 › Additional Error info:  Ctrl+Shift+X
^C
[3 preload-host-spawn-strategy] Dropping 0x46800108d80 (3) because of connection closed                   
16:03:13.454 › close, isQuiting: null
[3:1209/160313.455472:FATAL:bus.cc(1246)] D-Bus connection was disconnected. Aborting. 
```

But adding the below in environment variables using [flatpak-kcm](https://github.com/KDE/flatpak-kcm ) causes issues.
SuperProductivity starts in X11, and if I only specify Wayland as a socket it exits.
```
ozone-platform-hint = auto
enable-features = WaylandWindowDecorations
```

**Comment by aripollak** [comment]
I think those might not be valid as environment variables. See [post here](https://github.com/johannesjo/super-productivity/issues/25#issuecomment-2525217727) about how to use native Wayland.

**Comment by aripollak** [comment]
> But adding the below in flatpak-kcm solved it for some reason.

Hm, were there any error messages from the `override` command? Did you install the package system-wide? I wonder if you can't override the setting per-user if a package is installed system-wide. I assume flatpak-kcm is using the same mechanism as the commandline.

What's the output from the following commands?
```sh
flatpak list | grep SuperProductivity
flatpak override --show com.super_productivity.SuperProductivity
flatpak override --show user com.super_productivity.SuperProductivity
```


> Side question: would it be possible to make the Flatpak autodetect if the user is using X11 or Wayland.

That's possible, but I'm not comfortable doing that for only the Flatpak, for the following reasons:
* Electron Wayland support has not really felt stable yet (see #44543 for the latest basic issue I ran into)
* It's not on by default for upstream official Super Productivity packages either, and I think it would be confusing to have different defaults
* A user needing to turn off Wayland-default mode for the flatpak would run into the same issues as you're currently running into to enable it
* Almost all of the functionality for the app currently works as expected in Xwayland; the only exception that I know of is idle tracking

**Comment by aripollak** [comment]
Whoops, I meant `flatpak override --show --user com.super_productivity.SuperProductivity` for the broken command.

**Comment by aripollak** [comment]
I ran the override command and it's been working for me under GNOME Wayland. Make sure not to use `sudo`, since you want to override the flatpak settings for your regular user, not root.
